# Generated by Django 2.1.7 on 2019-03-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
