# Generated by Django 2.1.7 on 2019-03-26 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_auto_20190326_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='propietario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL),
        ),
    ]
